### ISSUE TITLE
请问老哥这个项目要怎样运行呢？

### ISSUE THREAD

**Issue by JuneCN** [CicholGricenchos/tiny-c#1]
前辈你好，我正在学习编译原理这门课，同时也在自学ruby（未到入门级），想参考你的代码。我在debian上clone了您的项目，但是在执行上遇到了问题，不知道该怎么让test文件夹下的sum.c之类的.c文件跑出结果，还望前辈不吝赐教！

**Comment by CicholGricenchos** [comment]
要看test文件夹里的测试用例，test_xxx.rb是可以直接运行的。单独用的话要先require那几样东西，然后
```ruby
tokens = Tokenizer.new.tokenize(code)
sexp = Parser.new.parse(tokens)
result = Compiler.new.compile(sexp)
```
code是源码字符串，result就是汇编。不过这个代码很久了，我不确保现在还能跑的通，应该有64位的gcc是可以跑的。
